platform :ios, '10.0'
use_frameworks!

target 'ECDHESSwift_Example' do
  pod 'ECDHESSwift', :path => '../'
  pod 'JOSESwift', '~> 1.8'

  target 'ECDHESSwift_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
